#!/usr/bin/env ruby

require 'optparse'

options = { width: 5, height: 5 }
OptionParser.new do |opts|
  opts.banner = "Usage: #{__FILE__}"

  opts.on('-w', '--width WIDTH', Integer, 'Set the width of the table the robot is on. Default: 5') do |w|
    options[:width] = w
  end

  opts.on('-h', '--height HEIGHT', Integer, 'Set the height of the table the robot is on. Default: 5') do |h|
    options[:height] = h
  end
end.parse!

require_relative 'lib/toy_robot'

table = ToyRobot::Table.new(height: options[:height], width: options[:width])
robot = ToyRobot::Robot.new(table)
command_parser = ToyRobot::CommandParser.new(robot)

commands = File.read(ARGV[0]).split("\n")
commands.each do |cmd|
  begin
    command_parser.call(cmd)
  rescue ToyRobot::PlacementError, ToyRobot::PositionError, ToyRobot::CommandError
  end
end
