#!/usr/bin/env ruby
require 'bundler/setup'
require_relative 'lib/toy_robot'
require_relative 'lib/toy_robot/command_parser'

command_parser = ToyRobot::CommandParser.new

if ARGV.size > 0
  require_relative 'lib/toy_robot/file_parser'

  file_parser = ToyRobot::FileParser.new(command_parser, ARGV[0])
  file_parser.call
else
  require_relative 'lib/toy_robot/command_line_parser'

  command_line_parser = ToyRobot::CommandLineParser.new(command_parser)
  command_line_parser.call
end
