#!/usr/bin/env ruby

require_relative 'lib/toy_robot'

robot = ToyRobot::Robot.new
command_parser = ToyRobot::CommandParser.new(robot)

commands = File.read(ARGV[0]).split("\n")
commands.each do |cmd|
  begin
    command_parser.call(cmd)
  rescue ToyRobot::PlacementError, ToyRobot::PositionError, ToyRobot::CommandError
  end
end
